import {LandscapeRenderer} from '../../../render.js?v=studio-1';
import {defaults} from '../../../document.js?v=studio-1';
const save=async(name,data)=>{const response=await fetch('/__grainy_studio_save/'+name,{method:'POST',body:data});if(!response.ok)throw Error('Save failed: '+name);};
document.querySelector('#run').onclick=async()=>{const renderer=new LandscapeRenderer(),button=document.querySelector('#run');button.disabled=true;document.querySelector('#grid').replaceChildren();const seeds=[1565559100,...Array.from({length:19},(_,i)=>((i+1)*2654435761)>>>0)],contact=document.createElement('canvas');contact.width=1920;contact.height=1512;const ctx=contact.getContext('2d');ctx.fillStyle='#191919';ctx.fillRect(0,0,1920,1512);ctx.fillStyle='#ddd';ctx.font='20px system-ui';const refs=[...document.querySelectorAll('.refs img')];await Promise.all(refs.map(i=>i.decode()));refs.forEach((image,i)=>ctx.drawImage(image,i*960,0,960,488));
 try{for(let i=0;i<20;i++){const seed=seeds[i],canvas=document.createElement('canvas');canvas.width=960;canvas.height=540;canvas.getContext('2d').drawImage(renderer.render({...defaults,seed},960,540),0,0);const blob=await new Promise(resolve=>canvas.toBlob(resolve));await save(String(i+1).padStart(2,'0')+'.png',blob);const image=document.createElement('img');image.src=URL.createObjectURL(blob);const figure=document.createElement('figure'),caption=document.createElement('figcaption');caption.textContent=(i+1)+' · '+seed;figure.append(image,caption);document.querySelector('#grid').append(figure);const x=i%5*384,y=512+Math.floor(i/5)*250;ctx.drawImage(canvas,x,y,384,216);ctx.fillText((i+1)+' · '+seed,x+6,y+240);document.querySelector('#status').textContent=(i+1)+' / 20';await new Promise(resolve=>setTimeout(resolve,0));}
 const sheet=await new Promise(resolve=>contact.toBlob(resolve));await save('contact-sheet.png',sheet);await save('metrics.json',JSON.stringify({date:'2026-10-07',preset:'Ember',seeds,count:20,width:960,height:540}));document.querySelector('#sheet').src=URL.createObjectURL(sheet);document.querySelector('#status').textContent='20 / 20 saved.';
 }catch(error){document.querySelector('#status').textContent=error.message;}finally{renderer.destroy();button.disabled=false;}};

// Show the saved review immediately when the page is reopened.
try {const result=await fetch('./metrics.json');if(result.ok){const m=await result.json();for(let i=0;i<m.count;i++){const figure=document.createElement('figure'),image=document.createElement('img'),caption=document.createElement('figcaption');image.src=String(i+1).padStart(2,'0')+'.png';image.alt='Ember '+(i+1);caption.textContent=(i+1)+' · '+m.seeds[i];figure.append(image,caption);document.querySelector('#grid').append(figure);}document.querySelector('#sheet').src='./contact-sheet.png';document.querySelector('#status').textContent=m.count+' saved variants';}}catch{}
