/**
 * Экспорт SVG в файл
 */
export class SVGExporter {
    constructor(settings) {
        this.settings = settings;
    }

    /**
     * Экспортировать SVG элемент в файл
     * @param {SVGElement} svgElement
     * @param {string} filename
     * @param {Object} options - Опции экспорта
     * @param {boolean} options.removeInteractive - Удалить интерактивные элементы
     * @param {boolean} options.optimizeSize - Оптимизировать размер
     */
    exportToFile(svgElement, filename = 'grid.svg', options = {}) {
        // Клонируем SVG для экспорта
        const clonedSvg = svgElement.cloneNode(true);
        
        // Удаляем интерактивные элементы если нужно
        if (options.removeInteractive) {
            this.removeInteractiveElements(clonedSvg);
        }
        
        // Сериализуем SVG в строку
        const serializer = new XMLSerializer();
        const svgString = serializer.serializeToString(clonedSvg);
        
        // Создаем blob и скачиваем
        const blob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        
        setTimeout(() => URL.revokeObjectURL(url), 100);
    }
    
    /**
     * Удалить интерактивные элементы из SVG
     * @param {SVGElement} svg
     */
    removeInteractiveElements(svg) {
        // Удаляем элементы с классами интерактивности
        const interactiveSelectors = [
            '.resize-handle',
            '.hover-overlay',
            '[data-interactive="true"]',
            '[class*="handle"]',
            '[class*="hover"]'
        ];
        
        interactiveSelectors.forEach(selector => {
            const elements = svg.querySelectorAll(selector);
            elements.forEach(el => el.remove());
        });
        
        // Удаляем обработчики событий из атрибутов
        const allElements = svg.querySelectorAll('*');
        allElements.forEach(el => {
            ['onclick', 'onmouseover', 'onmouseout', 'onmousedown', 'onmouseup'].forEach(attr => {
                el.removeAttribute(attr);
            });
        });
    }
    
    /**
     * Получить чистый SVG без интерактивных элементов
     * @param {SVGElement} svgElement
     * @returns {SVGElement}
     */
    getCleanSVG(svgElement) {
        const cloned = svgElement.cloneNode(true);
        this.removeInteractiveElements(cloned);
        return cloned;
    }

    /**
     * Создать полный SVG документ для экспорта
     * @param {string} content
     * @param {string} width
     * @param {string} height
     * @param {string} viewBox
     * @returns {string}
     */
    createExportSVG(content, width, height, viewBox) {
        return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${width}" height="${height}" viewBox="${viewBox}" 
     xmlns="http://www.w3.org/2000/svg" 
     xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>Grid Generator Export</title>
    <desc>Generated by Grid Generator for Lunnen packaging</desc>
    ${content}
</svg>`;
    }

    /**
     * Экспортировать настройки в JSON файл
     * @param {Object} data - Данные для экспорта
     * @param {string} filename
     */
    exportSettings(data, filename = 'grid-settings.json') {
        const jsonString = JSON.stringify(data, null, 2);
        
        const blob = new Blob([jsonString], { type: 'application/json;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        
        URL.revokeObjectURL(url);
    }

    /**
     * Импортировать настройки из JSON
     * @param {File} file
     * @returns {Promise<Object>} - Промис с данными из файла
     */
    async importSettings(file) {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            
            reader.onload = (e) => {
                try {
                    const jsonString = e.target.result;
                    const data = JSON.parse(jsonString);
                    resolve(data);
                } catch (error) {
                    reject(error);
                }
            };
            
            reader.onerror = () => reject(new Error('Failed to read file'));
            reader.readAsText(file);
        });
    }
}

