export const LINE_DENSITY_MIN_PERCENT = 1;
export const LINE_DENSITY_MAX_PERCENT = 320;
export const LINE_DENSITY_MIN = LINE_DENSITY_MIN_PERCENT / 100;
export const LINE_DENSITY_MAX = LINE_DENSITY_MAX_PERCENT / 100;

