export const SVG = Object.freeze({
    EXPORT_STROKE_WIDTH: '0.088194444',
    DISPLAY_STROKE_WIDTH: '1'
});

export const DEFAULT_SETTINGS = Object.freeze({
    frontWidth: 500,
    frontHeight: 500,
    thickness: 50,
    boxColor: '#404040',
    gridModule: 5.0505,
    margins: 2,
    marginsUnit: 'mod',
    columnCount: 12,
    rowCount: 12,
    rowHeight: 7,
    linkMode: 'module',
    fontSizeUnit: 'mod',
    lineHeightUnit: 'mod',
    lockedModule: false,
    lockedMargins: false,
    lockedModuleValue: null,
    lockedMarginsValue: null,
    headlineSize: 1.5,
    lineHeight: 2,
    tracking: -0.015,
    useXHeight: false,
    headlineFontWeight: 500,
    textSize: 0.5,
    textLineHeight: 1,
    textTracking: 0,
    useXHeight2: false,
    textFontWeight: 500,
    captionSize: 0.5,
    captionLineHeight: 1,
    captionTracking: 0,
    useXHeightCaption: false,
    captionFontWeight: 500,
    lunnenDisplaySize: 3,
    lunnenDisplayLineHeight: 4,
    lunnenDisplayTracking: 0,
    useXHeightLunnenDisplay: false,
    showDimensions: false,
    showLabels: false,
    showSidePanels: true,
    showColumns: true,
    showRows: true,
    showBaseline: true,
    showObjects: true
});
