/**
 * Экспорт SVG в файл
 */
export class SVGExporter {
    constructor(settings) {
        this.settings = settings;
    }

    /**
     * Экспортировать SVG элемент в файл
     * @param {SVGElement} svgElement
     * @param {string} filename
     */
    exportToFile(svgElement, filename = 'grid.svg') {
        // Клонируем SVG для экспорта
        const clonedSvg = svgElement.cloneNode(true);
        
        // Получаем размеры
        const width = clonedSvg.getAttribute('width');
        const height = clonedSvg.getAttribute('height');
        const viewBox = clonedSvg.getAttribute('viewBox');
        
        // Создаем чистый SVG для экспорта
        const svgContent = this.createExportSVG(clonedSvg.innerHTML, width, height, viewBox);
        
        // Создаем blob и скачиваем
        const blob = new Blob([svgContent], { type: 'image/svg+xml;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        
        URL.revokeObjectURL(url);
    }

    /**
     * Создать полный SVG документ для экспорта
     * @param {string} content
     * @param {string} width
     * @param {string} height
     * @param {string} viewBox
     * @returns {string}
     */
    createExportSVG(content, width, height, viewBox) {
        const hasValue = (value) => typeof value === 'string' && value.trim().length > 0;
        const stripUnit = (value) => {
            if (!hasValue(value)) return NaN;
            const parsed = parseFloat(value);
            return Number.isFinite(parsed) ? parsed : NaN;
        };
        const fallbackDimension = (primaryKey) => {
            if (this.settings && typeof this.settings.get === 'function') {
                const primary = this.settings.get(primaryKey);
                const thickness = this.settings.get('thickness');
                if (typeof primary === 'number') {
                    const extra = typeof thickness === 'number' ? thickness * 2 : 0;
                    return primary + extra;
                }
            }
            return 100;
        };
        
        const fallbackWidth = fallbackDimension('frontWidth');
        const fallbackHeight = fallbackDimension('frontHeight');
        
        let resolvedViewBox = hasValue(viewBox) ? viewBox.trim() : '';
        if (!resolvedViewBox) {
            const numericWidth = stripUnit(width);
            const numericHeight = stripUnit(height);
            const vbWidth = Number.isFinite(numericWidth) ? numericWidth : fallbackWidth;
            const vbHeight = Number.isFinite(numericHeight) ? numericHeight : fallbackHeight;
            resolvedViewBox = `0 0 ${vbWidth} ${vbHeight}`;
        }
        
        const viewBoxParts = resolvedViewBox.split(/\s+/);
        const vbWidth = parseFloat(viewBoxParts[2]) || fallbackWidth;
        const vbHeight = parseFloat(viewBoxParts[3]) || fallbackHeight;
        
        const normalizeDimension = (dimension, fallback) => {
            if (hasValue(dimension)) {
                return dimension.trim();
            }
            return `${fallback}mm`;
        };
        
        const resolvedWidth = normalizeDimension(width, vbWidth);
        const resolvedHeight = normalizeDimension(height, vbHeight);
        
        return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${resolvedWidth}" height="${resolvedHeight}" viewBox="${resolvedViewBox}" 
     xmlns="http://www.w3.org/2000/svg" 
     xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>Grid Generator Export</title>
    <desc>Generated by Grid Generator for Lunnen packaging</desc>
    ${content}
</svg>`;
    }

    /**
     * Экспортировать настройки в JSON файл
     * @param {string} filename
     */
    exportSettings(filename = 'grid-settings.json') {
        const settingsJSON = this.settings.toJSON();
        
        const blob = new Blob([settingsJSON], { type: 'application/json;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        
        URL.revokeObjectURL(url);
    }

    /**
     * Импортировать настройки из JSON
     * @param {File} file
     * @returns {Promise<void>}
     */
    async importSettings(file) {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            
            reader.onload = (e) => {
                try {
                    const json = e.target.result;
                    this.settings.fromJSON(json);
                    resolve();
                } catch (error) {
                    reject(error);
                }
            };
            
            reader.onerror = () => reject(new Error('Failed to read file'));
            reader.readAsText(file);
        });
    }
}

